import type {
  AbilityDefinition,
  BattleDefinition,
  ContentPack,
  LocalizedText,
  StoryNode,
  UnitTemplate,
} from '../game/types';

const t = (zh: string, en: string): LocalizedText => ({ 'zh-CN': zh, 'en-US': en });

const potion: AbilityDefinition = {
  id: 'healing-potion',
  name: t('治疗药剂', 'Healing Potion'),
  description: t('附赠动作。恢复2d4+2点生命。', 'Bonus action. Restore 2d4+2 HP.'),
  target: 'self',
  cost: 'bonus',
  range: 0,
  kind: 'heal',
  healing: { dice: '2d4', bonus: 2 },
  resourceCost: { key: 'potion', amount: 1 },
};

const heroes: UnitTemplate[] = [
  {
    id: 'mira-champion',
    name: t('米拉', 'Mira'),
    role: t('人类·冠军战士', 'Human · Champion Fighter'),
    team: 'heroes',
    level: 3,
    maxHp: 31,
    ac: 18,
    speed: 6,
    initiative: 2,
    saves: { str: 5, con: 5, dex: 2 },
    color: 0xb94f42,
    accent: 0xffc46b,
    resources: { secondWind: 2, actionSurge: 1, potion: 1 },
    tags: ['fighter'],
    abilities: [
      {
        id: 'longsword',
        name: t('长剑', 'Longsword'),
        description: t('近战攻击，命中造成1d8+3挥砍伤害。', 'Melee attack for 1d8+3 slashing damage.'),
        target: 'enemy',
        cost: 'action',
        range: 1,
        kind: 'attack',
        attackBonus: 5,
        damage: { dice: '1d8', bonus: 3, type: 'slashing' },
      },
      {
        id: 'second-wind',
        name: t('第二风', 'Second Wind'),
        description: t('附赠动作。恢复1d10+3点生命。', 'Bonus action. Restore 1d10+3 HP.'),
        target: 'self',
        cost: 'bonus',
        range: 0,
        kind: 'heal',
        healing: { dice: '1d10', bonus: 3 },
        resourceCost: { key: 'secondWind', amount: 1 },
      },
      {
        id: 'action-surge',
        name: t('动作如潮', 'Action Surge'),
        description: t('用尽动作后立即获得一个额外动作。', 'After spending your action, gain one additional action.'),
        target: 'self',
        cost: 'free',
        range: 0,
        kind: 'utility',
        utility: 'action-surge',
        resourceCost: { key: 'actionSurge', amount: 1 },
      },
      potion,
    ],
  },
  {
    id: 'sable-thief',
    name: t('塞布尔', 'Sable'),
    role: t('精灵·盗贼', 'Elf · Thief Rogue'),
    team: 'heroes',
    level: 3,
    maxHp: 24,
    ac: 15,
    speed: 6,
    initiative: 4,
    saves: { dex: 5, int: 3, wis: 1 },
    color: 0x3a816f,
    accent: 0x8cf0c9,
    resources: { potion: 1 },
    tags: ['rogue', 'sneak-attack'],
    abilities: [
      {
        id: 'shortbow',
        name: t('短弓', 'Shortbow'),
        description: t('远程攻击。满足条件时追加2d6偷袭伤害。', 'Ranged attack. Adds 2d6 Sneak Attack when eligible.'),
        target: 'enemy',
        cost: 'action',
        range: 6,
        kind: 'attack',
        attackBonus: 5,
        damage: { dice: '1d6', bonus: 3, type: 'piercing' },
      },
      {
        id: 'dagger',
        name: t('匕首', 'Dagger'),
        description: t('近战攻击。满足条件时追加2d6偷袭伤害。', 'Melee attack. Adds 2d6 Sneak Attack when eligible.'),
        target: 'enemy',
        cost: 'action',
        range: 1,
        kind: 'attack',
        attackBonus: 5,
        damage: { dice: '1d4', bonus: 3, type: 'piercing' },
      },
      {
        id: 'steady-aim',
        name: t('稳定瞄准', 'Steady Aim'),
        description: t('附赠动作。放弃本回合移动，下一次攻击获得优势。', 'Bonus action. Give up movement to gain Advantage on the next attack.'),
        target: 'self',
        cost: 'bonus',
        range: 0,
        kind: 'utility',
        utility: 'steady-aim',
      },
      {
        id: 'hide',
        name: t('隐匿', 'Hide'),
        description: t('附赠动作。附近没有敌人时藏入阴影，下一次攻击获得优势。', 'Bonus action. Hide when no enemy is adjacent and gain Advantage on the next attack.'),
        target: 'self',
        cost: 'bonus',
        range: 0,
        kind: 'utility',
        utility: 'hide',
      },
      potion,
    ],
  },
  {
    id: 'orin-evoker',
    name: t('奥林', 'Orin'),
    role: t('侏儒·塑能师', 'Gnome · Evoker Wizard'),
    team: 'heroes',
    level: 3,
    maxHp: 18,
    ac: 12,
    speed: 5,
    initiative: 1,
    saves: { int: 5, wis: 3, dex: 1 },
    color: 0x6255a5,
    accent: 0xb9a7ff,
    resources: { slot1: 4, slot2: 2, potion: 1 },
    tags: ['wizard', 'evoker'],
    abilities: [
      {
        id: 'fire-bolt',
        name: t('火焰箭', 'Fire Bolt'),
        description: t('塑能戏法。命中造成1d10火焰伤害；落空时仍造成一半伤害。', 'Evocation cantrip. Deals 1d10 fire damage; a miss still deals half.'),
        target: 'enemy',
        cost: 'action',
        range: 6,
        kind: 'attack',
        attackBonus: 5,
        damage: { dice: '1d10', type: 'fire', halfOnMiss: true },
      },
      {
        id: 'magic-missile',
        name: t('魔法飞弹', 'Magic Missile'),
        description: t('消耗1环法术位。自动造成3d4+3力场伤害。', 'Spend a level 1 slot. Automatically deal 3d4+3 force damage.'),
        target: 'enemy',
        cost: 'action',
        range: 7,
        kind: 'auto-damage',
        damage: { dice: '3d4', bonus: 3, type: 'force' },
        resourceCost: { key: 'slot1', amount: 1 },
      },
      {
        id: 'thunderwave',
        name: t('雷鸣波', 'Thunderwave'),
        description: t('消耗1环法术位。体质豁免，造成2d8雷鸣伤害并推开目标。', 'Spend a level 1 slot. Constitution save for 2d8 thunder damage and a push.'),
        target: 'enemy',
        cost: 'action',
        range: 1,
        kind: 'save',
        save: { ability: 'con', dc: 13 },
        damage: { dice: '2d8', type: 'force', halfOnSave: true },
        resourceCost: { key: 'slot1', amount: 1 },
        push: 2,
      },
      {
        id: 'chromatic-orb',
        name: t('繁彩球', 'Chromatic Orb'),
        description: t('消耗1环法术位。命中造成3d8火焰伤害。', 'Spend a level 1 slot. Hit for 3d8 fire damage.'),
        target: 'enemy',
        cost: 'action',
        range: 6,
        kind: 'attack',
        attackBonus: 5,
        damage: { dice: '3d8', type: 'fire' },
        resourceCost: { key: 'slot1', amount: 1 },
      },
      potion,
    ],
  },
];

const enemies: UnitTemplate[] = [
  {
    id: 'ash-thrall',
    name: t('灰烬尸兵', 'Ash Thrall'),
    role: t('近战亡灵', 'Undead skirmisher'),
    team: 'enemies',
    maxHp: 13,
    ac: 13,
    speed: 5,
    initiative: 1,
    saves: { str: 2, dex: 1, con: 2, wis: 0 },
    color: 0x62686c,
    accent: 0xe3b56c,
    abilities: [
      {
        id: 'rusted-blade',
        name: t('锈蚀弯刀', 'Rusted Blade'),
        description: t('近战攻击。', 'Melee attack.'),
        target: 'enemy',
        cost: 'action',
        range: 1,
        kind: 'attack',
        attackBonus: 4,
        damage: { dice: '1d6', bonus: 2, type: 'slashing' },
      },
    ],
  },
  {
    id: 'cinder-archer',
    name: t('余火弓手', 'Cinder Archer'),
    role: t('远程亡灵', 'Undead archer'),
    team: 'enemies',
    maxHp: 10,
    ac: 12,
    speed: 5,
    initiative: 3,
    saves: { dex: 3, con: 1, wis: 0 },
    color: 0x76614e,
    accent: 0xff8c45,
    abilities: [
      {
        id: 'cinder-bow',
        name: t('余火箭', 'Cinder Bow'),
        description: t('远程攻击。', 'Ranged attack.'),
        target: 'enemy',
        cost: 'action',
        range: 6,
        kind: 'attack',
        attackBonus: 4,
        damage: { dice: '1d6', bonus: 2, type: 'piercing' },
      },
      {
        id: 'bone-knife',
        name: t('骨刀', 'Bone Knife'),
        description: t('近战攻击。', 'Melee attack.'),
        target: 'enemy',
        cost: 'action',
        range: 1,
        kind: 'attack',
        attackBonus: 3,
        damage: { dice: '1d4', bonus: 1, type: 'piercing' },
      },
    ],
  },
  {
    id: 'ember-hound',
    name: t('烬牙猎犬', 'Ember Hound'),
    role: t('结群野兽', 'Pack hunter'),
    team: 'enemies',
    maxHp: 18,
    ac: 13,
    speed: 7,
    initiative: 3,
    saves: { dex: 3, con: 2, wis: 1 },
    color: 0x7f342a,
    accent: 0xffb24d,
    tags: ['pack-tactics'],
    abilities: [
      {
        id: 'ember-bite',
        name: t('烬牙撕咬', 'Ember Bite'),
        description: t('近战攻击。与盟友围攻时获得优势。', 'Melee attack. Gains Advantage when an ally surrounds the target.'),
        target: 'enemy',
        cost: 'action',
        range: 1,
        kind: 'attack',
        attackBonus: 4,
        damage: { dice: '1d8', bonus: 2, type: 'fire' },
      },
    ],
  },
  {
    id: 'ash-warden',
    name: t('信标守望者', 'Beacon Warden'),
    role: t('仪式首领', 'Ritual guardian'),
    team: 'enemies',
    maxHp: 52,
    ac: 15,
    speed: 5,
    initiative: 2,
    saves: { str: 5, dex: 1, con: 5, wis: 2 },
    color: 0x8b4334,
    accent: 0xffd27a,
    resources: { flare: 2 },
    tags: ['boss'],
    abilities: [
      {
        id: 'warden-glaive',
        name: t('守望长戟', 'Warden Glaive'),
        description: t('沉重的近战攻击。', 'A heavy melee strike.'),
        target: 'enemy',
        cost: 'action',
        range: 1,
        kind: 'attack',
        attackBonus: 5,
        damage: { dice: '1d10', bonus: 3, type: 'slashing' },
      },
      {
        id: 'beacon-flare',
        name: t('信标闪焰', 'Beacon Flare'),
        description: t('远程火焰爆发。敏捷豁免，成功时伤害减半。', 'A ranged burst of fire. Dexterity save for half damage.'),
        target: 'enemy',
        cost: 'action',
        range: 4,
        kind: 'save',
        save: { ability: 'dex', dc: 13 },
        damage: { dice: '2d6', bonus: 1, type: 'fire', halfOnSave: true },
        resourceCost: { key: 'flare', amount: 1 },
        tags: ['area'],
      },
    ],
  },
];

const battles: BattleDefinition[] = [
  {
    id: 'outer-ward',
    name: t('外环庭院', 'Outer Ward'),
    objective: t('击溃守卫。利用断墙获得掩护。', 'Defeat the guards. Use the broken walls as cover.'),
    width: 9,
    height: 6,
    terrain: [
      { x: 4, y: 0, kind: 'blocked' },
      { x: 4, y: 1, kind: 'cover' },
      { x: 4, y: 4, kind: 'cover' },
      { x: 4, y: 5, kind: 'blocked' },
      { x: 5, y: 2, kind: 'difficult' },
      { x: 5, y: 3, kind: 'difficult' },
    ],
    heroes: [
      { id: 'hero-mira', templateId: 'mira-champion', x: 1, y: 2 },
      { id: 'hero-sable', templateId: 'sable-thief', x: 1, y: 1 },
      { id: 'hero-orin', templateId: 'orin-evoker', x: 1, y: 4 },
    ],
    enemies: [
      { id: 'outer-thrall-a', templateId: 'ash-thrall', x: 7, y: 1 },
      { id: 'outer-thrall-b', templateId: 'ash-thrall', x: 7, y: 4 },
      { id: 'outer-archer', templateId: 'cinder-archer', x: 8, y: 2 },
    ],
  },
  {
    id: 'beacon-heart',
    name: t('信标核心', 'Beacon Heart'),
    objective: t('击败守望者。相邻时可消耗动作熄灭仪式柱，每根仪式柱使首领AC+1。', 'Defeat the Warden. An adjacent hero can spend an action to disable a pylon; each active pylon grants the boss +1 AC.'),
    width: 9,
    height: 7,
    bossUnitId: 'boss-warden',
    terrain: [
      { x: 4, y: 3, kind: 'difficult' },
      { x: 3, y: 3, kind: 'difficult' },
      { x: 5, y: 3, kind: 'difficult' },
      { x: 4, y: 2, kind: 'difficult' },
      { x: 4, y: 4, kind: 'difficult' },
      { x: 2, y: 1, kind: 'cover' },
      { x: 2, y: 5, kind: 'cover' },
      { x: 6, y: 1, kind: 'cover' },
      { x: 6, y: 5, kind: 'cover' },
    ],
    heroes: [
      { id: 'hero-mira', templateId: 'mira-champion', x: 1, y: 3 },
      { id: 'hero-sable', templateId: 'sable-thief', x: 1, y: 2 },
      { id: 'hero-orin', templateId: 'orin-evoker', x: 1, y: 4 },
    ],
    enemies: [
      { id: 'boss-warden', templateId: 'ash-warden', x: 6, y: 3 },
      { id: 'boss-hound', templateId: 'ember-hound', x: 7, y: 2 },
      { id: 'boss-thrall', templateId: 'ash-thrall', x: 7, y: 4 },
    ],
    objects: [
      { id: 'north-pylon', name: t('北侧仪式柱', 'North Pylon'), x: 4, y: 1, kind: 'pylon', active: true },
      { id: 'south-pylon', name: t('南侧仪式柱', 'South Pylon'), x: 4, y: 5, kind: 'pylon', active: true },
    ],
  },
];

const story: StoryNode[] = [
  {
    id: 'briefing',
    type: 'choice',
    eyebrow: t('契约 01 · 边境急件', 'Contract 01 · Frontier Dispatch'),
    title: t('灰烬信标', 'The Ashen Beacon'),
    text: t(
      '北境信标已经熄灭七天。没有灯火，山口另一侧的商队与村镇将在下一场黑潮中失去警告。你们抵达时，守门人的残影仍在门前徘徊。',
      'The northern beacon has been dark for seven days. Without its flame, caravans and villages beyond the pass will face the next black tide without warning. At the gate, the keeper’s echo still wanders.',
    ),
    quote: t('“火焰记得每一个守望者，也记得每一个逃兵。”', '“The flame remembers every watcher—and every deserter.”'),
    choices: [
      {
        id: 'soothe-echo',
        label: t('向残影许诺重燃信标', 'Promise the echo you will relight the beacon'),
        description: t('魅力（说服）+3，对抗DC 12。', 'Charisma (Persuasion) +3 vs DC 12.'),
        check: {
          label: t('安抚守门人', 'Soothe the keeper'),
          actor: t('塞布尔', 'Sable'),
          ability: t('说服', 'Persuasion'),
          modifier: 3,
          dc: 12,
          successText: t('残影让开道路，余温缠绕在旅团的武器上。', 'The echo yields, leaving a thread of warmth on the company’s weapons.'),
          failureText: t('残影发出尖啸，冰冷的灰尘穿过所有人的肺腑。', 'The echo shrieks, and cold ash tears through every lung.'),
          successEffects: [{ type: 'setFlag', key: 'openingAdvantage', value: true }],
          failureEffects: [{ type: 'damageParty', amount: 2 }],
          next: 'approach',
        },
      },
      {
        id: 'find-service-way',
        label: t('寻找维护工留下的暗门', 'Search for the keepers’ service passage'),
        description: t('智力（调查）+5，对抗DC 13。', 'Intelligence (Investigation) +5 vs DC 13.'),
        check: {
          label: t('寻找暗门', 'Find the hidden way'),
          actor: t('奥林', 'Orin'),
          ability: t('调查', 'Investigation'),
          modifier: 5,
          dc: 13,
          successText: t('齿轮后的窄道仍能使用，你们从守军侧翼进入庭院。', 'The narrow passage behind the gears still works. You enter the ward from the flank.'),
          failureText: t('暗门的配重崩断，碎石砸向旅团。', 'The passage counterweight snaps, showering the company with stone.'),
          successEffects: [{ type: 'setFlag', key: 'openingAdvantage', value: true }],
          failureEffects: [{ type: 'damageParty', amount: 3 }],
          next: 'approach',
        },
      },
      {
        id: 'force-gate',
        label: t('让米拉撞开大门', 'Have Mira break the gate'),
        description: t('力量（运动）+5，对抗DC 12。', 'Strength (Athletics) +5 vs DC 12.'),
        check: {
          label: t('破门', 'Break the gate'),
          actor: t('米拉', 'Mira'),
          ability: t('运动', 'Athletics'),
          modifier: 5,
          dc: 12,
          successText: t('门闩断裂。守卫来不及吞下储藏室里的药剂。', 'The bar splinters. The guards never reach the potions in their cache.'),
          failureText: t('大门倒向错误的一侧，旅团被木梁与铁钉擦伤。', 'The gate falls the wrong way, raking the company with timber and iron.'),
          successEffects: [{ type: 'addResource', key: 'potion', amount: 1 }],
          failureEffects: [{ type: 'damageParty', amount: 4 }],
          next: 'approach',
        },
      },
    ],
  },
  {
    id: 'approach',
    type: 'narrative',
    eyebrow: t('外环庭院', 'Outer Ward'),
    title: t('守卫仍在履行最后一道命令', 'The guards still obey their final order'),
    text: t(
      '尸兵从断墙后抬起锈蚀武器。庭院中央的灰烬正逆风飘向塔顶，说明某种仪式仍在抽取山中的热量。',
      'Thralls raise rusted weapons behind the broken walls. Ash drifts against the wind toward the tower, feeding a ritual that still draws warmth from the mountain.',
    ),
    next: 'outer-battle',
  },
  {
    id: 'outer-battle',
    type: 'battle',
    eyebrow: t('战斗遭遇', 'Combat Encounter'),
    title: t('外环守军', 'Outer Ward Guard'),
    text: t('击溃尸兵，进入信标内部。', 'Defeat the thralls and enter the beacon.'),
    battleId: 'outer-ward',
    next: 'after-outer',
  },
  {
    id: 'after-outer',
    type: 'choice',
    eyebrow: t('探索遭遇', 'Exploration Encounter'),
    title: t('塔内只剩下一次停留的机会', 'There is time for one search'),
    text: t('螺旋阶梯开始震动。守望者已经察觉入侵，你们只能调查一处区域。', 'The spiral stair begins to shake. The Warden knows you are here; there is time to investigate one place.'),
    choices: [
      {
        id: 'restore-rune',
        label: t('修复维护室里的断裂符文', 'Repair the broken maintenance rune'),
        description: t('智力（奥秘）+5，对抗DC 13。成功后预先熄灭一根仪式柱。', 'Intelligence (Arcana) +5 vs DC 13. Success disables one ritual pylon.'),
        check: {
          label: t('重绘符文', 'Restore the rune'),
          actor: t('奥林', 'Orin'),
          ability: t('奥秘', 'Arcana'),
          modifier: 5,
          dc: 13,
          successText: t('北侧仪式柱的脉冲停止了。', 'The north pylon falls silent.'),
          failureText: t('符文反噬，炽热纹路灼伤旅团。', 'The rune lashes back, burning the company.'),
          successEffects: [{ type: 'setFlag', key: 'northPylonDisabled', value: true }],
          failureEffects: [{ type: 'damageParty', amount: 2 }],
          next: 'camp',
        },
      },
      {
        id: 'search-armory',
        label: t('搜索封闭的守卫武库', 'Search the sealed watch armory'),
        description: t('智力（调查）+5，对抗DC 12。成功后每名英雄获得一瓶药剂。', 'Intelligence (Investigation) +5 vs DC 12. Success grants each hero a potion.'),
        check: {
          label: t('搜索武库', 'Search the armory'),
          actor: t('塞布尔', 'Sable'),
          ability: t('调查', 'Investigation'),
          modifier: 5,
          dc: 12,
          successText: t('三只密封药瓶仍有微弱光泽。', 'Three sealed vials still hold a faint glow.'),
          failureText: t('一枚旧弩机被触发，弩矢穿过队伍。', 'An old crossbow trap fires through the party.'),
          successEffects: [{ type: 'addResource', key: 'potion', amount: 1 }],
          failureEffects: [{ type: 'damageParty', amount: 2 }],
          next: 'camp',
        },
      },
      {
        id: 'follow-flame',
        label: t('追踪逆流而上的灰烬', 'Follow the ash flowing upward'),
        description: t('提前看清守望者的仪式，首领战首次攻击获得优势。', 'Read the Warden’s ritual and gain Advantage on the first attack of the boss battle.'),
        effects: [{ type: 'setFlag', key: 'bossAdvantage', value: true }],
        next: 'camp',
      },
    ],
  },
  {
    id: 'camp',
    type: 'choice',
    eyebrow: t('短休', 'Short Rest'),
    title: t('螺旋阶梯下的片刻喘息', 'A breath beneath the spiral stair'),
    text: t('仪式的脉冲越来越快。旅团只能选择一种整备方式。', 'The ritual pulse quickens. The company can prepare in only one way.'),
    choices: [
      {
        id: 'mend',
        label: t('包扎伤口', 'Bind wounds'),
        description: t('全员恢复50%最大生命，第二风恢复1次。', 'Restore 50% max HP to all heroes and one use of Second Wind.'),
        effects: [
          { type: 'healPartyPercent', percent: 0.5 },
          { type: 'restoreResource', key: 'secondWind', amount: 1 },
        ],
        next: 'boss-intro',
      },
      {
        id: 'focus',
        label: t('重整法术与呼吸', 'Refocus spell and breath'),
        description: t('全员恢复25%最大生命，恢复1个一环法术位，首领战首次攻击获得优势。', 'Restore 25% max HP, one level 1 spell slot, and Advantage on the first boss attack.'),
        effects: [
          { type: 'healPartyPercent', percent: 0.25 },
          { type: 'restoreResource', key: 'slot1', amount: 1 },
          { type: 'setFlag', key: 'bossAdvantage', value: true },
        ],
        next: 'boss-intro',
      },
      {
        id: 'press-on',
        label: t('趁守望者尚未完成仪式立即进攻', 'Press the attack before the ritual completes'),
        description: t('全员恢复15%最大生命，并预先熄灭北侧仪式柱。', 'Restore 15% max HP and disable the north pylon.'),
        effects: [
          { type: 'healPartyPercent', percent: 0.15 },
          { type: 'setFlag', key: 'northPylonDisabled', value: true },
        ],
        next: 'boss-intro',
      },
    ],
  },
  {
    id: 'boss-intro',
    type: 'narrative',
    eyebrow: t('信标核心', 'Beacon Heart'),
    title: t('守望者把自己铸进了最后一道命令', 'The Warden forged himself into his final command'),
    text: t(
      '塔顶的火盆已经变成一道倒悬的黑焰。两根仪式柱为盔甲中的巨人输送力量。熄灭仪式柱会削弱他的防御，也会消耗宝贵的动作。',
      'The brazier has become an inverted black flame. Two ritual pylons feed power into the armored giant. Disabling them weakens his defense, but costs precious actions.',
    ),
    quote: t('“信标不能熄灭。山下的人可以。”', '“The beacon must endure. Those below it need not.”'),
    next: 'boss-battle',
  },
  {
    id: 'boss-battle',
    type: 'battle',
    eyebrow: t('首领遭遇', 'Boss Encounter'),
    title: t('信标守望者', 'The Beacon Warden'),
    text: t('击败守望者，决定信标的命运。', 'Defeat the Warden and decide the beacon’s fate.'),
    battleId: 'beacon-heart',
    next: 'final-choice',
  },
  {
    id: 'final-choice',
    type: 'choice',
    eyebrow: t('最终抉择', 'Final Choice'),
    title: t('黑焰正在等待新的命令', 'The black flame awaits a new command'),
    text: t('守望者倒下后，信标仍有一次被重新定义的机会。山下的人会记住你们的选择。', 'With the Warden fallen, the beacon can be defined one final time. Those below will remember your choice.'),
    choices: [
      {
        id: 'rekindle',
        label: t('重燃警戒之火', 'Rekindle the warning flame'),
        description: t('守望山口，履行最初的契约。', 'Watch the pass and fulfill the original contract.'),
        effects: [{ type: 'gainRenown', amount: 3 }],
        next: 'ending-rekindled',
      },
      {
        id: 'seal',
        label: t('永久封印信标', 'Seal the beacon forever'),
        description: t('终止仪式，也让山口失去古老的保护。', 'End the ritual and the ancient protection with it.'),
        effects: [{ type: 'gainRenown', amount: 2 }],
        next: 'ending-sealed',
      },
      {
        id: 'claim',
        label: t('把黑焰带回旅团', 'Claim the black flame for the company'),
        description: t('获得危险的力量，并承担未来的代价。', 'Take a dangerous power—and its future cost.'),
        effects: [{ type: 'gainRenown', amount: 4 }],
        next: 'ending-claimed',
      },
    ],
  },
  {
    id: 'ending-rekindled',
    type: 'ending',
    endingId: 'rekindled',
    eyebrow: t('结局 · 守望', 'Ending · The Watch'),
    title: t('山口重新看见了光', 'The pass sees light again'),
    text: t('第一支商队在黎明前看见信标。旅团的名字沿着山路传开，而黑潮也在远处改变了方向。', 'The first caravan sees the beacon before dawn. The company’s name travels down the mountain road—and the black tide turns elsewhere.'),
  },
  {
    id: 'ending-sealed',
    type: 'ending',
    endingId: 'sealed',
    eyebrow: t('结局 · 无灯之路', 'Ending · The Unlit Road'),
    title: t('信标成为一座普通的废墟', 'The beacon becomes an ordinary ruin'),
    text: t('山下的人开始修筑瞭望塔与钟楼。他们失去了一件古老奇迹，也第一次把命运握在自己手中。', 'The villages build watchtowers and bell posts. They lose an ancient miracle and, for the first time, hold their fate in their own hands.'),
  },
  {
    id: 'ending-claimed',
    type: 'ending',
    endingId: 'claimed',
    eyebrow: t('结局 · 余烬债务', 'Ending · The Ember Debt'),
    title: t('旅团得到了一团会呼吸的火', 'The company gains a flame that breathes'),
    text: t('黑焰在遗物匣中安静燃烧。它会为下一份契约提供力量，也会在每个无人守夜的晚上低声数数。', 'The black flame burns quietly in the reliquary. It will lend power to the next contract—and count softly on every unwatched night.'),
  },
];

export const ashenBeaconPack: ContentPack = {
  manifest: {
    id: 'emberbound.ashen-beacon',
    version: '0.1.0',
    ruleset: 'emberbound-rules/0.1',
    title: t('余烬契约：灰烬信标', 'Emberbound: The Ashen Beacon'),
    locales: ['zh-CN', 'en-US'],
    contractIds: ['ashen-beacon'],
  },
  units: [...heroes, ...enemies],
  battles,
  contracts: [
    {
      id: 'ashen-beacon',
      title: t('灰烬信标', 'The Ashen Beacon'),
      subtitle: t('北境急件 · 建议等级3', 'Frontier Dispatch · Level 3'),
      description: t(
        '一座熄灭的山口信标、一名拒绝结束守望的亡者，以及一次会改变北境道路的选择。',
        'A darkened mountain beacon, a dead watcher who refuses to stand down, and a choice that will reshape the northern road.',
      ),
      estimatedMinutes: 30,
      startNodeId: 'briefing',
      story,
    },
  ],
};
